#
# Copyright (c) 2023 - for information on the respective copyright owner
# see the NOTICE file and/or the repository https://github.com/herdstat/herdstat-example.
#
# SPDX-License-Identifier: MIT
#

repositories:
  - herdstat

contribution-graph:
  filters:
    commits:
      - "Author.Name == 'github-actions' && Message matches 'Update contribution graph.*'"
